sources:
  - name: github_org
    type: github
    repo: apache/airflow
    enabled: true

  - name: github_kubernetes
    type: github
    repo: kubernetes/kubernetes
    enabled: false
s3:
  bucket: sgs-dev-data-bucket
  base_path: github/dev
  